repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.14
    hooks:
      - id: uv-lock
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.29
    hooks:
      - id: pymarkdown
