repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.7
    hooks:
      - id: uv-lock
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.33
    hooks:
      - id: pymarkdown
